name: "General issue"
description: |
  Report a general issue with Emacs+ (not Emacs itself)
title: "[General]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue.

        - Please remember that Emacs+ is just a formula for homebrew. 
        - If you have an issue with GNU Emacs, you should ask for help via mailing list.
        - If you have a question, feel free to use [discussions](https://github.com/d12frosted/homebrew-emacs-plus/discussions).
  - type: textarea
    id: build-output
    attributes:
      label: "Issue description"
      description: "A clear and concise description of the issue."
    validations:
      required: true
